name: Docker build huginn image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '.github/workflows/docker-build-huginn.yml'
      - 'huginn/**'

jobs:

  build:

    runs-on: ${{ (github.event_name == 'push') && fromJSON('[ "cirun-runner" ]') || 'ubuntu-latest' }}

    steps:
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "commit=$(git ls-remote https://github.com/huginn/huginn.git | head -n1 | awk '{print $1;}')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: keel
          key: ${{ runner.os }}-v1-${{ env.commit }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Check Out Repo huginn/huginn
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "huginn/huginn"
          ref: 'master'
          path: 'huginn-git'
          
      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Override prepare script
        id: override-prepare-script
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cp huginn/scripts/prepare huginn-git/docker/scripts/prepare
          cp huginn/multi-process/scripts/standalone-packages huginn-git/docker/multi-process/scripts/standalone-packages
        shell: bash

      - name: Apply patches
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mv ./huginn/patches/*.patch ./huginn-git
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cd ./huginn-git && git am *.patch
        shell: bash

      - name: Build and push docker image single process
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new_single_process
        uses: docker/build-push-action@v3
        with:
          context: ./huginn-git
          file: ./huginn/single-process/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: quay.io/unixfox/huginn-single-process:latest, quay.io/unixfox/huginn-single-process:build-${{ env.timestamp }}