name: Docker build LibreChat image

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/docker-build-librechat.yml'
      - 'librechat/**'

jobs:

  build:

    runs-on: 'ubuntu-latest'

    steps:
      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "tag=$(git ls-remote --refs --tags https://github.com/danny-avila/LibreChat.git | grep -v 'rc' | cut --delimiter='/' --fields=3 | sort --version-sort | tail --lines=1 | cut -d "v" -f2)" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v5

      - name: Check Out Repo LibreChat
        uses: actions/checkout@v5
        with:
          repository: "danny-avila/LibreChat"
          ref: 'main'
          path: 'librechat-git'

      - name: Copy custom Dockerfile
        run: |
          cp librechat/Dockerfile librechat-git/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push docker image
        id: docker_build_new
        uses: docker/build-push-action@v6
        with:
          context: ./librechat-git
          file: ./librechat-git/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/unixfox/librechat:latest, quay.io/unixfox/librechat:${{ env.tag }}
